import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavHome } from "./navbar/navbar-home-layout";
import TextHighlighter from "./components/TextHighlighter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tailwind UI Components",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`pt-[110px] pb-16 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavHome />
        <TextHighlighter>
          {children}
        </TextHighlighter>

      </body>
    </html>
  );
}
